# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0005_auto_20160115_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rank', models.IntegerField()),
                ('source', models.CharField(max_length=256, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='entries.Entry')),
            ],
        ),
    ]
