# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='definition',
            name='part_of_speech',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
