# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 00:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
