# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20160108_0003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
            ],
        ),
    ]
