# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20160109_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 11, 22, 50, 2, 954797, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
