# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='definition_source',
        ),
    ]
